"""
Django settings for photo-tagging-api project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6a#cl3!78759rf&2t-smwy%09s$*@s*-!7w*8_83-^(m$f$0%e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   
    'photos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'photo_tagging_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'photo_tagging_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# LLaVA (Google Colab) settings.
# Example: https://<your-ngrok-subdomain>.ngrok-free.app/analyze
LLAVA_COLAB_URL = os.getenv(
    'LLAVA_COLAB_URL', '')

LLAVA_PROMPT = os.getenv(
    'LLAVA_PROMPT',
    """You are a precise image captioning tool for a searchable database. 
Your goal is to describe ONLY what is visually verifiable in the frame. 
Do NOT infer emotions, intentions, or events happening outside the frame. 
Do NOT mention objects or people that are not fully visible or clearly identifiable. 
If only a part of a person is visible (e.g., a hand or a foot), do NOT tag the image as containing a 'person' or 'people'. Only mention the specific body part or object.

Provide the output in two strict sections:

SECTION 1: FACTUAL VISUAL INVENTORY (Keywords for Search)
- Subject: [Single primary object or entity in focus]
- Setting/Background: [Explicit description of environment (indoor/outdoor, surface, walls, sky)]
- Lighting: [Direction and quality, e.g., 'harsh sunlight from left', 'soft ambient indoor', 'dark shadows']
- Foreground Objects: [List only items clearly in front, e.g., 'blurred hand holding paper', 'coffee cup on table edge']
- Colors & Materials: [Dominant palette and textures, e.g., 'matte white paper', 'glossy red ceramic']

SECTION 2: STRUCTURED CAPTION
Write exactly 4 sentences.
1. Describe the main subject and its exact position in the frame.
2. Describe the immediate, visible background and lighting conditions.
3. Describe only the clearly visible details, textures, or text (if legible).
4. Describe the edges/cropping of the frame (what is cut off or partially visible).

CRITICAL RULES:
- If something is CUT OFF by the frame edge, describe it as 'partial' or 'cropped'. 
- Example: If only a hand holding a paper is visible, say: "A cropped view of a hand holding a white sheet of paper." DO NOT SAY "A person holding a paper."
- Do not guess gender, age, or species unless 100% unambiguous (e.g., clear adult face).
- Focus on concrete nouns and spatial relationships."""
)

LLAVA_TIMEOUT_SECONDS = int(os.getenv('LLAVA_TIMEOUT_SECONDS', '120'))
LLAVA_AUTH_TOKEN = os.getenv('LLAVA_AUTH_TOKEN', '')

FACE_DETECTION_ENABLED = os.getenv('FACE_DETECTION_ENABLED', '0').strip().lower() in {
    '1', 'true', 'yes', 'on'
}
FACE_ANALYSIS_MODEL_NAME = os.getenv('FACE_ANALYSIS_MODEL_NAME', 'buffalo_l')
FACE_ANALYSIS_CTX_ID = int(os.getenv('FACE_ANALYSIS_CTX_ID', '0'))
FACE_ANALYSIS_DET_SIZE = (
    int(os.getenv('FACE_ANALYSIS_DET_WIDTH', '640')),
    int(os.getenv('FACE_ANALYSIS_DET_HEIGHT', '640')),
)
FACE_ANALYSIS_PROVIDERS = [
    provider.strip()
    for provider in os.getenv('FACE_ANALYSIS_PROVIDERS', 'CPUExecutionProvider').split(',')
    if provider.strip()
]

# Tags you care about. If these words are present in the description, they are prioritized.
LLAVA_PREFERRED_TAGS = [
    'person',
    'food',
    'car',
    'dog',
    'cat',
    'child',
]

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.10.35',
    '10.19.214.238',
    '10.20.0.104',
    '172.20.10.4',
]


