"""
Django settings for photo-tagging-api project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os 


def env_list(name, default=''):
    return [
        item.strip()
        for item in os.getenv(name, default).split(',')
        if item.strip()
    ]


def env_bool(name, default='0'):
    return os.getenv(name, default).strip().lower() in {'1', 'true', 'yes', 'on'}


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-6a#cl3!78759rf&2t-smwy%09s$*@s*-!7w*8_83-^(m$f$0%e',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', '1')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   
    'photos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'photo_tagging_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'photo_tagging_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if env_bool('USE_POSTGRES', '0'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'photo_app'),
            'USER': os.getenv('POSTGRES_USER', 'photo_app'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'postgres'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('DJANGO_MEDIA_ROOT', BASE_DIR / 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PHOTO_API_AUTH_TOKEN = os.getenv('PHOTO_API_AUTH_TOKEN', '').strip()

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'photos.authentication.OptionalBearerTokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.getenv('DRF_PAGE_SIZE', '50')),
    'EXCEPTION_HANDLER': 'photos.responses.api_exception_handler',
}

LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# LLaVA (Google Colab) settings.
# Example: https://<your-ngrok-subdomain>.ngrok-free.app/analyze
LLAVA_COLAB_URL = os.getenv(
    'LLAVA_COLAB_URL', '')

LLAVA_PROMPT = os.getenv(
    'LLAVA_PROMPT',
    """Describe the image in plain English in no more than 5 normal sentences.
Return only the description text. Do not use headings, sections, bullet lists,
numbered lists, JSON, labels, or a separate keyword list.
Describe only what is visually verifiable in the image. Do not infer emotions,
intentions, events outside the frame, identity, gender, age, or species unless it is
unambiguous from the visible image.
Mention the main subject, visible setting, colors, shapes, materials, textures,
readable text, and cropped or partially visible objects when relevant.
If only a body part is visible, describe the body part, not a whole person.
If an animal-shaped toy or drawing is visible, describe it as a toy, plush,
drawing, or figurine, not as a real animal."""
)

LLAVA_TIMEOUT_SECONDS = int(os.getenv('LLAVA_TIMEOUT_SECONDS', '120'))
LLAVA_AUTH_TOKEN = os.getenv('LLAVA_AUTH_TOKEN', '')

FACE_DETECTION_ENABLED = os.getenv('FACE_DETECTION_ENABLED', '0').strip().lower() in {
    '1', 'true', 'yes', 'on'
}
FACE_ANALYSIS_MODEL_NAME = os.getenv('FACE_ANALYSIS_MODEL_NAME', 'buffalo_l')
FACE_ANALYSIS_CTX_ID = int(os.getenv('FACE_ANALYSIS_CTX_ID', '0'))
FACE_ANALYSIS_DET_SIZE = (
    int(os.getenv('FACE_ANALYSIS_DET_WIDTH', '640')),
    int(os.getenv('FACE_ANALYSIS_DET_HEIGHT', '640')),
)
FACE_ANALYSIS_PROVIDERS = [
    provider.strip()
    for provider in os.getenv('FACE_ANALYSIS_PROVIDERS', 'CPUExecutionProvider').split(',')
    if provider.strip()
]

# Tags you care about. If these words are present in the description, they are prioritized.
LLAVA_PREFERRED_TAGS = [
    'person',
    'food',
    'car',
    'dog',
    'cat',
    'child',
]

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost,192.168.10.35,10.19.214.238,10.20.0.104,172.20.10.4',
)

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


