# Generated by Django 6.0.1 on 2026-01-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='tags',
            field=models.JSONField(blank=True, help_text='Список тегов, полученных от нейросети', null=True, verbose_name='Теги'),
        ),
    ]
