# Generated by Django 6.0.1 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_alter_processedimage_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedimage",
            name="face_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Face count"),
        ),
        migrations.AddField(
            model_name="processedimage",
            name="faces",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Detected faces with bounding boxes and confidence scores.",
                verbose_name="Faces",
            ),
        ),
    ]
