# Generated by Django 6.0.1 on 2026-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_processedimage_faces_and_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='tags',
            field=models.JSONField(blank=True, help_text='Tags returned by the image analysis pipeline.', null=True, verbose_name='Tags'),
        ),
    ]
